### ISSUE TITLE
[BUG] "Sensitive command hostname" & "Sensitive command username" or "Sensitive Command Information" missing from alerts

### ISSUE THREAD

**Issue by wilmerism** [thinkst/canarytokens#280]
**Describe the bug**
Hi, Over last week or so, im noticing less information coming on the email alerts. 

**To Reproduce**
Example attatched is a sensative command toen for "reg.exe" I attatch a old and recent alert. 

**Expected behavior**
to see the host name and username who triggered alert.
Though i give one example - This is on multiple canary tokens (all of the same type "sensitive command Canarytoken")

**Screenshots**
![Old alert](https://github.com/thinkst/canarytokens/assets/18171236/e01dabf2-2573-4549-9661-ee6366c95227)
![Today alert](https://github.com/thinkst/canarytokens/assets/18171236/ca1a51f6-5dc7-4b53-bf1b-6ce2b3cd28d8)

Side note / Possibly related also over theis last week - some other sensitive command Canarytokens "Sensitive command hostname" & "Sensitive command username" have been coming in with the charictors are in upper and lower case differnt to what comes. example >

![alternate caps](https://github.com/thinkst/canarytokens/assets/18171236/e8637b1b-7c3f-4687-8008-cee76ff833f3)

**Comment by wilmerism** [comment]
2nd side note. I now notice the positioning of "Sensitive command hostname" & "Sensitive command username" is inconsistant. Inteh above examples it on one line called "Sensitive Command Information"

and on others there are two seperate rows for this

**Comment by wleightond** [comment]
Hi @wilmerism,

Thank you for raising this! We also noticed that this information was missing and fixed it in PR #268. The change from a single row to separate fields is a design choice made as part of a recent upgrade to Canarytokens.

The unpredictable case appears to be a result of 0x20 encoding, and the mangling making it to emails is a genuine bug, thank you for pointing it out. We have fixed it in PR #284.

**Comment by wilmerism** [comment]
Hi thanks for fix. 95% are now all good. however i still getting a few through missing data. >> 

![Screenshot 2023-09-05 171325](https://github.com/thinkst/canarytokens/assets/18171236/dd7064e2-8b6d-4611-aef8-72605149a3d3)

![Screenshot 2023-09-05 171242](https://github.com/thinkst/canarytokens/assets/18171236/dd20eecd-9d47-4353-807d-5f3563ccca2d)

**Comment by wilmerism** [comment]
still getting, fyi below no host name and no executed in.

Should i be creating new tokens at all ?

![cnanry](https://github.com/thinkst/canarytokens/assets/18171236/adacc1ff-d0c7-42a2-9743-8b0e03c6ae56)

**Comment by thinkst-pieter** [comment]
@wilmerism thanks for the update.

> still getting, fyi below no host name and no executed in.

Sorry that you are still running into this.

 I removed the stale tag and we will dig some more into this.

**Comment by thinkst-pieter** [comment]
Hi @wilmerism

> still getting, fyi below no host name and no executed in.

Our current suspicion is that the time between when the code was committed to master and when it was deployed on the production server is the culprit that caused your token to misbehave.

Can you please try again.
